from exceptions import *

except_func(raise_func)
except_func(myexcept_raise_func)